---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scaffold.taskapp.io
  resources:
  - scaffoldrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaffold.taskapp.io
  resources:
  - scaffoldrequests/status
  verbs:
  - get
  - patch
  - update
