{{- if eq .Values.github.auth "pat" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: crossplane-system
  name: {{ include "scaffold-operator.resourceName" (dict "suffix" "crossplane-secret-reader" "context" $) }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - crossplane-github-credentials
  verbs:
  - get
{{- end }}
